server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4000 #docker contact
          predicates:
            - Path=/api/v1/patients/**
          filters:
            - StripPrefix=0

          ## REST CLIENT -> http://localhost:4004/api/patients
          ## API GATEWAY -> http://patient-service:4000/
          ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients Array

        - id: api-docs-patients-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs
          ## REST_CLIENT -> http://localhost:4004/api-docs/patients
          ## API-GATEWAY -> http://patient-service:4000/v3/api-docs