### GET request to get all patients
GET http://localhost:4000/api/v1/patients
###

### POST request to create a new patient
POST http://localhost:4000/api/v1/patients/create
Content-Type: application/json

{
  "name": "Angelina Jolie",
  "email": "jolie555@gmail.com",
  "address": "123 hallway",
  "dateOfBirth": "1990-09-09",
  "registeredDate": "2025-01-04"
}

###

### PUT request to update patient
PUT http://localhost:4000/api/v1/patients/update/123e4567-e89b-12d3-a456-426614174004
Content-Type: application/json

{
  "name": "Boa Hancock updated",
  "email": "hotaf@gmail.com",
  "address": "115 hallway",
  "dateOfBirth": "1990-09-09"
}

#####

### DELETE request to delete patient
DELETE http://localhost:4000/api/v1/patients/delete/123e4567-e89b-12d3-a456-426614174004
###